### ISSUE TITLE
spring-boot version higher than 1.3.3

### ISSUE THREAD

**Issue by Jason2002** [cloudframeworks-springcloud/user-guide-springcloud#34]
当授权服务，账户服务spring-boot版本高于1.3.5, 1.3.3 时，
注册用户抛异常如下
{"timestamp":1522318457409,"status":500,"error":"Internal Server Error","exception":"feign.FeignException","message":"status 403 reading AuthServiceClient#createUser(User); content:\n{\"timestamp\":1522318457398,\"status\":403,\"error\":\"Forbidden\",\"message\":\"Access Denied\",\"path\":\"/uaa/users\"}","path":"/accounts/“}

**Comment by smarthadron** [comment]
seems that you are using 1.5.x, try to set security.oauth2.resource.filter-order = 3

**Comment by Jason2002** [comment]
thans you. smarthadron, i sot it, but new issue appears.
feign.FeignException: status 500 reading AuthServiceClient#createUser(User); content:
{"timestamp":1522388480079,"status":500,"error":"Internal Server Error","exception":"org.springframework.dao.InvalidDataAccessApiUsageException","message":"The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!","path":"/uaa/users"}
	at feign.FeignException.errorStatus(FeignException.java:62) ~[feign-core-9.5.0.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:91) ~[feign-core-9.5.0.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-9.5.0.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.0.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.0.jar:na]
